# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Deep Paper Pool
tagline:             'hmmm'
description:         'A paper a day?'
url:		     https://ht93.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ht93
  url:               https://ht93.github.io
  email:             hetong1115@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
